# Generated by Django 4.1.2 on 2022-10-28 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_categorymodel_lateststorymodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lateststorymodel",
            name="price",
        ),
    ]
