# Generated by Django 4.1.2 on 2022-11-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_educationmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopwriterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(max_length=800)),
                (
                    "image",
                    models.ImageField(
                        default="default/topwriter.png", upload_to="topwriter/image/"
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("category", models.ManyToManyField(to="core.categorymodel")),
            ],
        ),
    ]
